config/routes.rb
Rails.application.routes.draw do
  
  root "users#home"
  get "users/me", :to => "users#about", as: 'users_about'
  get "users/index", :to => "users#index", as: 'users_index'
  get "users/home", :to => "users#home", as: 'users_home'
  get "users/search", :to => "users#search", as: 'users_search'
 
  get "users/finalpage", :to => "users#finalpage", as: 'users_finalpage'
  post "users/finalpage"
end

app/models/users.rb
class User < ActiveRecord::Base
  
end

app/models/zipcode.rb
class Zipcode < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def fetch(url)
		schoolsArray = Array.new()
		resp = Net::HTTP.get_response(URI.parse(url))
	    data = resp.body
	    downloadedData = JSON.parse(data)
	end


	def createHighSchoolDictionary(zip)
		data 	= fetch("https://data.cityofchicago.org/resource/2m8w-izji.json")
		schools = []

		for school in data
			if (school["zip"] == zip)
				modSchool = Hash.new("")
				modSchool["safe"] = school["safe"]
				modSchool["name_of_school"] = school["name_of_school"]
				modSchool["location"] = school["location"]
				modSchool["street_address"] = school["street_address"]
				modSchool["zip_code"] = school["zip"]
				modSchool["website"] = school["website"]
				modSchool["effective_leaders"] = school["effective_leaders"]
				modSchool["_4_year_graduation_rate_percentage_2013"] =  school["_4_year_graduation_rate_percentage_2013"]
				schools.push modSchool
			end
		end

		return schools
	end


	def createElementarySchoolDictionary(zip)
		data = fetch("https://data.cityofchicago.org/resource/tj8h-mnuv.json")
		schools = Array.new
		for school in data
		if (school["zip_code"] == zip)
			modSchool = Hash.new("")
			modSchool["safe"] = school["safe"]
			modSchool["name_of_school"] = school["name_of_school"]
			modSchool["location"] = school["location"]
			modSchool["street_address"] = school["street_address"]
			modSchool["zip_code"] = school["zip_code"]
			modSchool["website"] = school["website"]
			modSchool["effective_leaders"] = school["effective_leaders"]
			modSchool["student_attendance_percentage_2013"] =  school["student_attendance_percentage_2013"]
			schools.push modSchool
			end
		end
		return schools
	end


	def createEarlyChildhoodDictionary(zip)
		data = fetch("https://data.cityofchicago.org/resource/ck29-hb9r.json")
		schools = Array.new
		for school in data
			if (school["zip"] == zip)
				modSchool = Hash.new("")
				modSchool["weekday_availability"] = school["weekday_availability"]
				modSchool["site_name"] = school["site_name"]
				modSchool["location"] = school["location"]
				modSchool["street_address"] = school["address"]
				modSchool["zip_code"] = school["zip"]
				modSchool["url"] = school["url"]
				modSchool["duration_hours"] = school["duration_hours"]
				modSchool["program_information"] =  school["program_information"]
				modSchool["quality_rating"] = school["quality_rating"]
				schools.push modSchool
			end
		end
		return schools
	end


	def createParkDictionary(zip)
		data  = fetch("https://data.cityofchicago.org/resource/wwy2-k7b3.json")
		parks = []

		for park in data
			if(park["zip"] == zip)
				modPark = Hash.new("")
				modPark["park_name"] = park["park_name"]
				modPark["zip"] = park["zip"]
				modPark["street_address"] = park["street_address"]
				modPark["dog_friendly"] = park["dog_friendly"]
				modPark["playground_park"] = park["playground_park"]
				modPark["fitness_center"] = park["fitness_center"]
				modPark["pool_outdoor"] =  park["pool_outdoor"]
				modPark["basketball_courts"] = park["basketball_courts"]
				modPark["baseball_jr_softball_t_ball"] = park["baseball_jr_softball_t_ball"]
				modPark["community_garden"] =  park["community_garden"]
				parks.push modPark
			end
		end

		return parks
	end

	def validZip (userZip)
	zips = [60018, 60068, 60176, 60601, 60602, 60603, 60604, 60605, 60606, 60607, 60608, 60609, 60610, 60611, 60612, 60613, 60614, 60615, 60616, 60617, 60618, 60619, 60620, 60621, 60622, 60623, 60624, 60625, 60626, 60628, 60630, 60631, 60632, 60634, 60636, 60637, 60639, 60640, 60641, 60642, 60643, 60644, 60645, 60646, 60647, 60649, 60651, 60652, 60653, 60654, 60655, 60656, 60657, 60659, 60660, 60661, 60706, 60707, 60714]
	zips.each do |zip|
	    if zip.to_s == userZip
			return true
		end
	end
	return false
end


	def collectAllData (personna, zip)
		allData = Hash.new("")
		if(!validZip(zip))
			allData["error"] = ["zip_not_in_chicago"]
		end
		allData["personna"] = personna
		allData["parks"] = createParkDictionary zip
		allData["highSchools"] = createHighSchoolDictionary zip
		allData["elementarySchools"] = createElementarySchoolDictionary zip
		allData["earlyChildHoodPrograms"] = createEarlyChildhoodDictionary zip

		return allData.to_json
	end


	def new
		@users = User.new
	end


	def home
	end


	def index
	end


	def about 
	end


	def search
	end


	def finalpage
		@personas = params[:persona]
	    @zipcode  = params[:zipcode]
		@result   = post(@zipcode, @personas)
	end


	private
		def post(zip, personas)
		    require "net/http"
		    require "uri"

			url = "https://api.narrativescience.com/v4/editorial/55b135718ff57d597c2fb6e6/story/"
			uri = URI.parse(url)
			https = Net::HTTP.new(uri.host, uri.port)
			https.use_ssl = true
			https.verify_mode = OpenSSL::SSL::VERIFY_NONE
			request = Net::HTTP::Post.new(uri.path, initheader = {'content-type' =>'application/json', 'x-ns-api-token' => Rails.application.secrets.ns_token, 'x-ns-accepts' => 'html', 'x-ns-template' => Rails.application.secrets.ns_template})

			request.body = collectAllData(personas,zip)
			
			response = https.request(request)

			response.body
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<hr class="featurette-divider">
      <!-- FOOTER -->
<footer>
	<p class="pull-right"><a href="#">Back to top</a></p>
	<p>&copy; 2015 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top navClose">
    
      <div class="container posMiddle posCenter">
        <div class="row">
          <div class="col-xs-4">
           <%= link_to "HOME", users_home_path, class:"btn btn-primary btn-lg" %>
       </div>

          <div  class="col-xs-4 logo">
              <%= link_to image_tag("logo.svg", alt: "logo")%>
          </div>

           <div class="col-xs-4">
              <%= link_to "ABOUT", users_about_path, class:"btn btn-primary btn-lg" %> 
           </div>
         </div>
      </div>

</nav>


    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>

    <title> Close to Home </title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    
  
  	
</head>
<body>

  <%= render "/layouts/navbar" %>
  <%= yield %>
  <%= render "/layouts/footer" %>

  </body>
</html>

app/views/users/_checkform.html.erb
<%= form_tag(users_finalpage_path) do -%>

<% end -%>

<%= form_tag('/users/finalpage', method: :get) do -%>
  <%= text_field_tag :persona %>
  <%= submit_tag 'Search', class: 'btn btn btn-primary btn-lg' %>
<% end -%>

app/views/users/_search_form.html.erb
<div class="row posRowMarginTop">
  <div class="col-lg-12 posCenter">
      <h4>Please enter zipcode AND select the school range that you are looking for:</h4>
  </div>
</div>

<%= form_tag(users_finalpage_path, method: :get) do %>
  <div class="row">
    <div class="col-sm-10 col-sm-offset-1 form-fields">
    
      <%= label_tag :zipcode, "Enter Zipcode" %>
      <span style="color:black;">
      
      <%= text_field_tag :zipcode %>
      </span>

    </div>
  </div>

  <div class="row">
    <radiogroup>
        <!-- <div class="posRowMarginTop posCenter"> -->
      <div class="col-sm-4">
          <%= image_tag("baby.svg", class:"img-circle",  alt:"Generic placeholder image", width:"140", height:"140")  %>
          <h3 class="mt-5"><%= label_tag 'Early Childhood' %></h3>
          <%= radio_button_tag 'persona', "baby", false, required: true, class: 'chkSizeLg' %>
      </div>
  	 
      <div class="col-sm-4">
        <%= image_tag("childhood.svg",  class:"img-circle",  alt:"Generic placeholder image", width:"140", height:"140")  %>
        <h3><%= label_tag 'Elementary School' %></h3>
        <%= radio_button_tag 'persona', "child", false, required: true, class: 'chkSizeLg' %> 
      </div>
  	  
    
    
      <div class="col-sm-4">
        <%= image_tag("teen.svg",  class:"img-circle",  alt:"Generic placeholder image", width:"140", height:"140")  %>
        <h3><%= label_tag 'High School' %></h3>
        <%= radio_button_tag 'persona', "teen", false, required: true, class: 'chkSizeLg' %>
      </div>
    </radiogroup>
    
  </div>

  <div class="row">
   <div class="text-center">
    <%= submit_tag 'Search', class: 'btn btn btn-danger btn-lg' %>
   </div>
  </div>
  
<% end %>

app/views/users/about.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    
    <title>Close To Home | About</title>

    
    
  </head>
<!-- NAVBAR
================================================== -->
  <body>
    <!--     about quill:
 -->

    <div class= "blue-bar results">
        <h4> NARRATIVES BY QUILL </h4>
    </div>
    
    <div class="blue-bar results">

      <h5> Data-Driven Communications at Machine Scale</h5>
      <p>
      Powered by artificial intelligence, Narrative Science Quill™ is an advanced natural language generation platform for the enterprise that creates data-driven communications at machine scale. It analyzes data from disparate sources, understands what is important, then generates perfectly written narratives to convey meaning for any intended consumer or business audience.</p>

      <div class="ns-link">
        <%= link_to "http://www.narrativescience.com/quill" %>
      </div>

    </div>
    
       <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

  </body>
</html>

app/views/users/finalpage.html.erb
<<<<<<< HEAD
<div class="blue-bar results">

		<%= @result.html_safe %>	

</div>

<!-- decide if you want what you had or the above, what i put -->

<!-- <div class="blue-bar results">
	<%#= @result.html_safe %></div>
		<div class="row">
   <div class="text-center">
    <%#= link_to "SEARCH AGAIN", users_search_path, class: "btn btn-danger btn-lg" %>
   </div>
  </div> -->

app/views/users/home.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
         
          <img class="first-slide" <%= link_to image_tag("slideone.svg", alt: "First slide") %>
        
          <div class="cotainer">
          <div class="carousel-caption first">
              <h1>Welcome to CLOSE To Home, a tool that helps you pinpoint valuable resources in your community</h1>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="second-slide"  <%= link_to image_tag("slidetwo.svg", alt: "Second slide") %>>
          <div class="container">
            <div class="carousel-caption">
              <h1>Just enter an address and the school ranges for your children to find public schools, parks and programs in your neighborhood.</h1>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="third-slide" <%= link_to image_tag("slidethree.svg", alt: "Third slide") %>>
          <div class="container">
            <div class="carousel-caption">
              <h1>Whether you are relocating to a new neighborhood or becoming a first-time parent, Close To Home will help you track down great resources for your family in your area.</h1>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only"> P </span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only"> N </span>
      </a>
    </div><!-- /.carousel -->
    <div>
    <div class="posRowMarginTop posRowMarginBottom">
    <div class="row">
      <div class="col-xs-12 posCenter">
     <%= link_to "ENTER", users_search_path, class: "btn btn-danger btn-lg" %>
     </div>
    </div> 
    </div>
</div>




    

    

app/views/users/search.html.erb
<div class="marketing">
  <div class="blue-bar">
      <%= render "search_form" %>
  </div>
</div>



          
          

app/views/users/search_form.html.erb
<div class="row posRowMarginTop">
  <div class="col-lg-12 posCenter">
      <h4>Please enter zipcode AND select the school range that you are looking for:</h4>
  </div>
</div>

<%= form_tag(users_finalpage_path, method: :get) do %>
  <div class="row">
    <div class="col-sm-10 col-sm-shift-1">
      <%= label_tag (:zipcode, "Enter Zipcode") %>
      <%= text_field_tag :zipcode, nil, required: true, placeholder: "ZIP CODE HERE" %>
    </div>
  </div>

  <div class="row">
    <radiogroup>
        <!-- <div class="posRowMarginTop posCenter"> -->
      <div class="col-sm-4">
          <%= image_tag("baby.svg", class:"img-circle",  alt:"Generic placeholder image", width:"140", height:"140")  %>
          <h3 class="mt-5"><%= label_tag 'Early Childhood' %></h3>
          <%= radio_button_tag 'persona', "baby", false, required: true, class: 'chkSizeLg' %>
      </div>
  	 
      <div class="col-sm-4">
        <%= image_tag("childhood.svg",  class:"img-circle",  alt:"Generic placeholder image", width:"140", height:"140")  %>
        <h3><%= label_tag 'Elementary School' %></h3>
        <%= radio_button_tag 'persona', "child", false, required: true, class: 'chkSizeLg' %> 
      </div>
  	  
    
    
      <div class="col-sm-4">
        <%= image_tag("teen.svg",  class:"img-circle",  alt:"Generic placeholder image", width:"140", height:"140")  %>
        <h3><%= label_tag 'High School' %></h3>
        <%= radio_button_tag 'persona', "teen", false, required: true, class: 'chkSizeLg' %>
      </div>
    </radiogroup>

    <!-- </div> -->
    <!-- /.row checkboxes -->
        <!-- </ul> -->
<!--         <div class="row">
          <div class="col-lg-12 posCenter posMiddle">
          <h4>Select any one option!</h4>
          </div>
        </div> -->
       <!-- </div>  -->
    
  </div>

  <div class="row">
    <%= submit_tag 'Search', class: 'btn btn btn-danger btn-lg' %>
  </div>
  
  
<% end %>